In [1]:
import torch
import numpy as np

In [5]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype = torch.float32)
#First axis length of 3 second axis length 4 , therefore rank two tensor

In [12]:
print(t.size() )
#and
print(t.shape)

torch.Size([3, 4])
torch.Size([3, 4])


In [13]:
len(t.shape)

2

In [15]:
torch.tensor(t.shape).prod() #number of elements in the tensor
#or use
t.numel()

12

In [ ]:
"""Reshaping makes use of the .reshape(n,m,...) function where n,m must always be the 
product n and m"""

In [16]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)
#squuezing removes all axis that have a length of 1

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [17]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)
#adds an axis with a length of 1

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [18]:
#flatten function 
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

print(flatten(t))

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
