In [1]:
import torch
import numpy as np

In [2]:
t = torch.Tensor()
type(t)

torch.Tensor

In [3]:
#tensor attributes
print(t.dtype) #datatype
print(t.device) #device
print(t.layout) #layout

torch.float32
cpu
torch.strided


In [4]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [8]:
#Creating tensors diffeerent ways, prefer factory functions
data = np.array([1,2,3])
type(data)
print(torch.Tensor(data)) #class constructor (copy)
print(torch.tensor(data)) #factory function (copy), BEST ONE
print(torch.as_tensor(data)) #factory function, mirror array (share), SECOND 
print(torch.from_numpy(data)) #factory function. mirror array (share)
#all factory functions allow torch.tensor(np.array([1,2,3], dtype=torch.float64))

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [9]:
#Creation Options without data
print(torch.eye(2))
print(torch.ones(2,2))
print(torch.zeros(2,2))
print(torch.rand(2,2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.7823, 0.8702],
        [0.3158, 0.9750]])
